### ISSUE TITLE
Server Spec

### ISSUE THREAD

**Issue by bacakomik** [bajpangosh/High-Traffic-wordpress-server-configuration#1]
What is server specifications for using that configuration?

**Comment by bajpangosh** [comment]
**Operating system and version:** Ubuntu-18.04 and Ubuntu-20.04
**Architecture:** 64-bit
**RAM** Minimum: 1 GB, **Recommended: 2 GB**
**Disk Space** Minimum: 20 GB, **Recommended: 40 GB**
